### ISSUE TITLE
3.5.3

### ISSUE THREAD

**Issue by iSpid3r** [SchizoDuckie/PimpMyuTorrent#16]
Not working with uTorrent 3.5.3

**Comment by garfield69** [comment]
duplicate of #14

broken with uTorrent 3.5.3 due to https://engineering.bittorrent.com/2018/02/22/httprpc-security-vulnerabilities-resolved-in-utorrent-bittorrent-and-utorrent-web/

a possible circumvention that you might like to give this a go:

install uTorrent prior to 3.5.1
use the pimp to set the parms
install uTorrent 3.5.3 (without un-installing the prior version)
this should just upgrade uTorrent to 3.5.3 while keeping your pimped settings.

**Comment by SeaHOH** [comment]
Go #19 to have a try.
